# DEFAULT CLAMPS
DEFAULT_HEIGHT_CLAMP = 1.5

# Default object attr
# MAIN VELOCITIES
DEFAULT_XY_VELOCITY = 1

# Default Environment attr
DEFAULT_TIME_DELAY = 2

# Special values
VOID = -1

DEFAULT_BRICKS_SIZE = 50